# Build stage
FROM node:14 as build-stage
WORKDIR /app
COPY services/webapp/package*.json /app/
RUN npm install
COPY services/webapp /app/
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY deploy/docker/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
